const express=require("express"),path=require("path"),Database=require("better-sqlite3"),QRCode=require("qrcode");
const app=express(),PORT=process.env.PORT||3000,db=new Database(process.env.DB_PATH||path.join(__dirname,"cantinho.db"));
db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),name TEXT,welcome TEXT);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,description TEXT,price REAL,category_id INTEGER,emoji TEXT,image TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS tables(id INTEGER PRIMARY KEY AUTOINCREMENT,number INTEGER UNIQUE);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,table_number INTEGER,status TEXT DEFAULT 'Recebido',observation TEXT,total REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,product_name TEXT,quantity INTEGER,unit_price REAL);`);
if(!db.prepare("SELECT 1 FROM settings WHERE id=1").get())db.prepare("INSERT INTO settings VALUES(1,?,?)").run("Cantinho dos Gigantes","Bem-vindo! Faça seu pedido pelo celular.");
if(!db.prepare("SELECT COUNT(*) c FROM categories").get().c){let q=db.prepare("INSERT INTO categories(name) VALUES(?)");["Lanches","Porções","Bebidas","Sobremesas"].forEach(x=>q.run(x))}
if(!db.prepare("SELECT COUNT(*) c FROM tables").get().c){let q=db.prepare("INSERT INTO tables(number) VALUES(?)");for(let i=1;i<=12;i++)q.run(i)}
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){let c=Object.fromEntries(db.prepare("SELECT id,name FROM categories").all().map(x=>[x.name,x.id])),q=db.prepare("INSERT INTO products(name,description,price,category_id,emoji) VALUES(?,?,?,?,?)");q.run("X-Burger","Pão, hambúrguer, queijo e molho especial.",25.9,c.Lanches,"🍔");q.run("X-Bacon","Hambúrguer, queijo e bacon.",28.9,c.Lanches,"🥓");q.run("Batata Frita","Porção crocante.",15.9,c["Porções"],"🍟");q.run("Refrigerante","Lata 350 ml.",6.9,c.Bebidas,"🥤");q.run("Brownie","Brownie quentinho.",12.9,c.Sobremesas,"🍫")}
app.use(express.json()),app.use(express.static(path.join(__dirname,"public")));
app.get("/api/menu",(req,res)=>res.json({settings:db.prepare("SELECT name,welcome FROM settings WHERE id=1").get(),categories:db.prepare("SELECT * FROM categories ORDER BY id").all(),products:db.prepare("SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.active=1 ORDER BY p.id").all()}));
app.get("/api/admin/products",(req,res)=>res.json(db.prepare("SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC").all()));
app.post("/api/orders",(req,res)=>{let{table,items,observation=""}=req.body;if(!Number(table)||!Array.isArray(items)||!items.length)return res.status(400).json({error:"Pedido inválido"});let get=db.prepare("SELECT id,name,price FROM products WHERE id=? AND active=1"),a=[],total=0;for(let i of items){let p=get.get(Number(i.product_id)),q=Math.max(1,Math.floor(Number(i.quantity)));if(!p)return res.status(400).json({error:"Produto inválido"});a.push({p,q}),total+=p.price*q}let tx=db.transaction(()=>{let o=db.prepare("INSERT INTO orders(table_number,observation,total) VALUES(?,?,?)").run(Number(table),String(observation),total),ins=db.prepare("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price) VALUES(?,?,?,?,?)");a.forEach(x=>ins.run(o.lastInsertRowid,x.p.id,x.p.name,x.q,x.p.price));return o.lastInsertRowid});res.json({ok:true,id:tx(),total})});
app.get("/api/orders",(req,res)=>{let a=db.prepare("SELECT * FROM orders ORDER BY id DESC").all();a.forEach(o=>o.items=db.prepare("SELECT product_name name,quantity,unit_price FROM order_items WHERE order_id=?").all(o.id));res.json(a)});
app.patch("/api/orders/:id",(req,res)=>{let ok=["Recebido","Em preparo","Pronto","Entregue","Cancelado"];if(!ok.includes(req.body.status))return res.status(400).json({error:"Status inválido"});db.prepare("UPDATE orders SET status=? WHERE id=?").run(req.body.status,Number(req.params.id));res.json({ok:true})});
app.put("/api/settings",(req,res)=>{db.prepare("UPDATE settings SET name=?,welcome=? WHERE id=1").run(String(req.body.name||"Cantinho dos Gigantes"),String(req.body.welcome||""));res.json({ok:true})});
app.post("/api/categories",(req,res)=>{try{let r=db.prepare("INSERT INTO categories(name) VALUES(?)").run(String(req.body.name||"").trim());res.json({id:r.lastInsertRowid})}catch(e){res.status(409).json({error:"Categoria já existe"})}});
app.post("/api/products",(req,res)=>{let x=req.body;if(!x.name||!Number(x.price)||!Number(x.category_id))return res.status(400).json({error:"Preencha os campos"});let r=db.prepare("INSERT INTO products(name,description,price,category_id,emoji,image) VALUES(?,?,?,?,?,?)").run(x.name,x.description||"",Number(x.price),Number(x.category_id),x.emoji||"🍔",x.image||"");res.json({id:r.lastInsertRowid})});
app.put("/api/products/:id",(req,res)=>{let x=req.body;db.prepare("UPDATE products SET name=?,description=?,price=?,category_id=?,emoji=?,image=?,active=? WHERE id=?").run(x.name,x.description||"",Number(x.price),Number(x.category_id),x.emoji||"🍔",x.image||"",x.active===0?0:1,Number(req.params.id));res.json({ok:true})});
app.get("/api/qrcode/:table",async(req,res)=>{let u=`${req.protocol}://${req.get("host")}/?mesa=${encodeURIComponent(req.params.table)}`;res.json({url:u,png:await QRCode.toDataURL(u,{width:400,margin:2})})});
app.get("/api/stats",(req,res)=>{let o=db.prepare("SELECT COUNT(*) c,COALESCE(SUM(total),0) total FROM orders").get();res.json({orders:o.c,total:o.total,products:db.prepare("SELECT COUNT(*) c FROM products").get().c,tables:db.prepare("SELECT COUNT(*) c FROM tables").get().c})});
app.get("/health",(req,res)=>res.json({ok:true}));app.listen(PORT,()=>console.log("Cantinho dos Gigantes na porta "+PORT));